[GLOBAL]
pants_version = "2.25.1"
backend_packages = [
    "pants.backend.python",
    "pants.backend.build_files.fmt.ruff"
]

[source]
marker_filenames = ["pyproject.toml"]

[python]
interpreter_constraints = ['==3.11.*']
enable_resolves = true
resolves = { python-default = "thirdparty/python/default.lock" }
